name: StarfallEX builder CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sex-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.CI_TOKEN }}
      
    - name: Load lua
      uses: leafo/gh-actions-lua@v13

    - name: Build AstroTrooper
      run: lua builder/builder.lua astronew astrotrooper.lua

    - name: Load AstroTrooper to artifact
      uses: actions/upload-artifact@v7
      with:
        path: astrotrooper_builded.lua
        archive: false
