name: StarfallEX builder CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sex-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build and minify code of AstroTrooper
      run: lua builder/builder.lua astronew astrotrooper.lua
      uses: leafo/gh-actions-lua@v13

    - name: Load AstroTrooper to artifact
    - uses: actions/upload-artifact@v7
      with:
        path: astrotrooper_builded.lua
        archive: false
